language: cpp
compiler:
  - gcc
  - clang
before_install: 
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libopencv-dev
before_script:
  - mkdir ./build
  - cd ./build
script:
  - cmake ..
  - make -j
notifications:
  email: false
